info:
  app:
    name: MyAPI
    description: My API for ...
    version: 1.0.0

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,loggers"


